name: excitesms
description: A Flutter package for sending SMS via the ExciteSMS API
version: 1.0.1
repository: https://github.com/ExciteSMS/excitesms

environment:
  sdk: ^3.0.5


# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
